services:
  # Backend Service (FastAPI)
  - type: web
    name: lucknow-guide-backend # Unique name for the backend service
    env: python
    plan: free # Use Render's free tier
    runtime: docker
    dockerfilePath: ./backend/Dockerfile # Path relative to repo root
    dockerContext: ./backend # Build context directory
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Match the Python version in your Dockerfile
      # CORRECTED SYNTAX for secrets from an Environment Group:
      - key: GROQ_API_KEY          # Must exactly match the key name in your Render secrets
        fromGroup: lucknow-guide-secrets # Specifies the Environment Group name
      - key: HUGGINGFACEHUB_API_TOKEN # Must exactly match the key name in your Render secrets
        fromGroup: lucknow-guide-secrets # Specifies the Environment Group name
    # Optional: Health check path for FastAPI
    healthCheckPath: /docs
    autoDeploy: yes # Redeploy automatically on pushes to the main branch

  # Frontend Service (Streamlit)
  - type: web
    name: lucknow-guide-frontend # Unique name for the frontend service
    env: python
    plan: free
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile # Path relative to repo root
    dockerContext: ./frontend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      # CRUCIAL: Tell the frontend the internal URL of the backend service on Render
      - key: BACKEND_URL
        # Render automatically resolves 'lucknow-guide-backend' to the internal service address
        value: http://lucknow-guide-backend:8000/query
    autoDeploy: yes

```

**Key Changes:**

* Removed the `fromSecretKeyRef` block.
* Added `fromGroup: lucknow-guide-secrets` directly under the `key` for both `GROQ_API_KEY` and `HUGGINGFACEHUB_API_TOKEN`.

**Next Steps:**

1.  **Replace** the content of your `render.yaml` file with the corrected version above.
2.  **Commit and Push** this change to your GitHub repository:
    ```bash
    git add render.yaml
    git commit -m "Fix: Correct render.yaml syntax for secret environment variables"
    git push origin main
    
